/*=========================================================================

    This file is part of vtkPOpenFOAMReader.

    vtkPOpenFOAMReader is free software: you can redistribute it
    and/or modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation, either version 3 of
    the License, or (at your option) any later version.

    vtkPOpenFOAMReader is distributed in the hope that it will be
    useful, but WITHOUT ANY WARRANTY; without even the implied
    warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with vtkPOpenFOAMReader.  If not, see
    <http://www.gnu.org/licenses/>.

=========================================================================*/
// Copyright (c) 2008 Takuya OSHIMA <oshima@eng.niigata-u.ac.jp>.
// All rights reserved.
// Date: 2008-08-31

#ifndef _pqOpenFOAMPanel_h
#define _pqOpenFOAMPanel_h

#include "pqAutoGeneratedObjectPanel.h"

class pqOpenFOAMPanel : public pqAutoGeneratedObjectPanel
{
  Q_OBJECT
public:
  pqOpenFOAMPanel(pqProxy *, QWidget *);

  ~pqOpenFOAMPanel() {}

protected slots:
  void onRefresh();
};

#endif
